spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
lotto:
  number-generator-base-url: "http://localhost:8888"
  number-generator:
    lotteryRunOccurrence: "0 55 11 * * 6"
  result-checker:
    lotteryRunOccurrence: "0 56 11 * * 6"